"""Model access and embeddings, through LangChain."""
from meta_evolver.llm.client import (
    DEFAULT_EMBED_DIMENSIONS,
    DEFAULT_EMBED_MODEL,
    DEFAULT_MODEL,
    DEPRECATED_SAMPLING_PARAMS,
    LLMError,
    ScriptedChatModel,
    TokenMeter,
    build_chat_model,
    build_rate_limiter,
    effective_model,
    invoke_text,
    message_text,
    model_name,
    qualify,
    sampling_params_deprecated,
    split_model,
    tool_call_message,
)
from meta_evolver.llm.embeddings import (
    Embedder,
    build_embeddings,
    cosine,
    hashed_embedding,
    l2_normalize,
)

__all__ = [
    "DEFAULT_EMBED_DIMENSIONS",
    "DEFAULT_EMBED_MODEL",
    "DEFAULT_MODEL",
    "DEPRECATED_SAMPLING_PARAMS",
    "Embedder",
    "LLMError",
    "ScriptedChatModel",
    "TokenMeter",
    "build_chat_model",
    "build_rate_limiter",
    "build_embeddings",
    "cosine",
    "effective_model",
    "hashed_embedding",
    "invoke_text",
    "l2_normalize",
    "message_text",
    "model_name",
    "qualify",
    "sampling_params_deprecated",
    "split_model",
    "tool_call_message",
]
